### ISSUE TITLE
Throws error when there's no results

### ISSUE THREAD

**Issue by lloydwatkin** [matrix-io/face-analytics#6]
``` bash
node_modules/face-analytics/index.js:34
                    "detections":response.body.result[0].detection, 
                                                     ^

TypeError: Cannot read property '0' of undefined
    at /home/lloyd/Sites/wonky-vege-facebook/node_modules/face-analytics/index.js:34:39
    at Request.handleRequestResponse [as _callback] (/home/lloyd/Sites/wonky-vege-facebook/node_modules/face-analytics/node_modules/unirest/index.js:461:25)
    at Request.self.callback (/home/lloyd/Sites/wonky-vege-facebook/node_modules/face-analytics/node_modules/unirest/node_modules/request/request.js:373:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/lloyd/Sites/wonky-vege-facebook/node_modules/face-analytics/node_modules/unirest/node_modules/request/request.js:1318:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/lloyd/Sites/wonky-vege-facebook/node_modules/face-analytics/node_modules/unirest/node_modules/request/request.js:1266:12)
    at emitNone (events.js:91:20)
```

**Comment by lloydwatkin** [comment]
Actually, it seems the API has changed, changing line 32 of `index.js` to:

``` javascript
                        if(response.status === 200) {
                                defer.resolve({
                                        "detections":response.body.results[0].data,
                                        "analytics": response.body.results[0].meta
                                });
```

Gets things moving

**Comment by brianofrokk3r** [comment]
Thanks @lloydwatkin for pointing this out! We'll do a PR on this today or tomorrow and clean it up.

**Comment by lloydwatkin** [comment]
No problem. Your master branch looks slightly different to the version on
npm  (although I'm not sure what is deployed in npm as there's no tags).

I've hacked my local copy to what I've said and it seems to be giving me
the results I wanted.

**Comment by brianofrokk3r** [comment]
@lloydwatkin should be good now

**Comment by lloydwatkin** [comment]
Could you publish to npm please?

**Comment by brianofrokk3r** [comment]
@lloydwatkin now as well!
